---
kind: pipeline
name: test

steps:
  - name: run tests
    image: node
    commands:
    - yarn
    - yarn run prepare
    - yarn run test

trigger:
  event:
    - push
    - pull_request
    - tag

---
kind: pipeline
name: publish-npm

steps:
  - name: prepare
    image: node
    commands:
    - yarn
    - yarn run prepare
  - name: publish on npm
    image: plugins/npm
    settings:
      username: yarmo_eu
      password:
        from_secret: npm_token
      email:
        from_secret: npm_email

depends_on:
  - test

trigger:
  event:
    - tag
