pipeline:
  dev:
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/proxy/Dockerfile
      repo: keyoxide/doip-proxy
      tags: dev
    when:
      event: push
  stable:
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/proxy/Dockerfile
      repo: keyoxide/doip-proxy
      tags: stable
    when:
      event: tag
  tag:
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/proxy/Dockerfile
      repo: keyoxide/doip-proxy
      auto_tag: true
    when:
      event: tag

depends_on:
  - test